language: go
env:
    global:
        - VET_VERSIONS="1.6 1.7 1.8 1.9 1.10 tip"
        - LINT_VERSIONS="1.7 1.8 1.9 1.10 tip"
go:
    - "1.6"
    - "1.7"
    - "1.8"
    - "1.9"
    - "1.10"
    - tip
matrix:
    fast_finish: true
    allow_failures:
        - go: tip
go_import_path: github.com/trustelem/ldap
install:
    - go get gopkg.in/asn1-ber.v1
    - go get github.com/trustelem/ldap
    - go get code.google.com/p/go.tools/cmd/cover || go get golang.org/x/tools/cmd/cover
    - go get github.com/golang/lint/golint || true
    - go build -v ./...
script:
    - make test
    - make fmt
    - if [[ "$VET_VERSIONS"  == *"$TRAVIS_GO_VERSION"* ]]; then make vet; fi
    - if [[ "$LINT_VERSIONS" == *"$TRAVIS_GO_VERSION"* ]]; then make lint; fi
